13 edit financial information
NextUp-comedy/api-nc pull request #15
Opened 2022-07-31 13:46 UTC by RandSohail

2022-08-01 06:17 UTC, Jood80 commented on src/controllers/users/addFinancialInformation.ts
> +
I have a style suggestion here, -not to mention that `notExist` should be capitalized-:

what about we handle the exception names differently?
instead of `NOT_EXIST` we can name it with 401 error messsage `UNAUTHORIZED`.
We use that for the commonly known http error exception messages (`NOT_FOUND`, `FORBIDDEN`,...etc )., and we customize it if necessarily.
You would like to see [how nest.js handle it here](https://docs.nestjs.com/exception-filters)
So we send a strict messages from our back the front will translate this to `I don't like your face now, please try at morning`

2022-08-01 07:03 UTC, AymanSami98 approved these changes

2022-08-01 10:38 UTC, Jood80 approved these changes

2022-08-01 12:51 UTC, zaher-aa approved these changes

2022-08-01 12:51 UTC, zaher-aa commented on src/bin/index.ts
> +      Logger.info(`Listening on http://${bind}`);
Make it small
```suggestion
      logger.info(`Listening on http://${bind}`);
```

2022-08-01 21:45 UTC, Jood80 commented on .eslintrc.json
> +    ]
We'll need to remove this as @zaher-aa suggested a better type earlier today:
`[ClientResponse, Record<string, never>]`

2022-08-02 14:21 UTC, Ibrahim-Jarada approved these changes

2022-08-10 07:31 UTC, Ibrahim-Jarada approved these changes

2022-08-10 07:31 UTC, AymanSami98 approved these changes

2022-08-10 07:44 UTC, Jood80 requested changes

2022-08-10 07:44 UTC, Jood80 commented on package.json
> +    "build:db": "cross-env NODE_ENV=development npm run migrate:reset && cross-env NODE_ENV=development ts-node-dev ./src/database/fakeData/index.ts && cross-env NODE_ENV=development npm run migrate:
Optionally, please check if we can use `seed` & `generate` CLI commands to create a dummy data & generate a new migration files. -for consistency sake only-

2022-08-10 07:44 UTC, Jood80 commented on src/controllers/auth/forgetPassword.ts
> +      name, userRoleId, id,
I believe the frontend is sending `roleId` not `userRoleId`. please update that

2022-08-10 07:44 UTC, Jood80 commented on src/controllers/auth/signup.ts
> +      freeToBePaidRevenue: 0,
Any chance these numbers might not be zero as a default value?
in case it's not, please add a `constant` to make easier changes  into their initial values.

2022-08-10 07:44 UTC, Jood80 commented on src/controllers/auth/userAuth.ts
> +      userRoleId,
same here `roleId`

2022-08-10 07:44 UTC, Jood80 commented on src/helpers/validation/signupSchema.ts
> +  name: Joi.string().required().messages({ 'string.empty': 'name can\'t be empty', 'any.required': 'name is required' }),
`cannot` maybe? would make it more readable, easier to distinguish for the frontend

2022-08-10 07:44 UTC, Jood80 commented on src/services/user/user.ts
> +// import { IUserInfo } from '../../interfaces'
remove this comment please

2022-08-10 08:19 UTC, Jood80 commented on src/controllers/auth/signup.ts
> +      freeToBePaidRevenue: 0,
suggestion:
`ACC_PAID_REVENUE_INIT_VALUE`

2022-08-10 08:35 UTC, Jood80 commented on package.json
> +    "build:db": "cross-env NODE_ENV=development npm run migrate:reset && cross-env NODE_ENV=development ts-node-dev ./src/database/fakeData/index.ts && cross-env NODE_ENV=development npm run migrate:
**PS:** it seems that umzug handle seeding differently from sequeilze cli, as you can't see a direct seeding option amongst [their commands](https://github.com/marcbachmann/umzug-cli)
**However**, [check this example on how someone implement it](https://github.com/sequelize/umzug/issues/24#issuecomment-591313032)
you don't need to apply it in here, just FYI :)

2022-08-10 09:56 UTC, Jood80 approved these changes

2022-08-10 11:06 UTC, merged