20 user management
NextUp-comedy/api-nc pull request #23
Opened 2022-08-13 12:58 UTC by RandSohail

2022-08-13 13:06 UTC, AymanSami98 approved these changes

2022-08-15 08:47 UTC, Jood80 requested changes

2022-08-15 08:47 UTC, Jood80 commented on src/controllers/users/addUser.ts
> +      createdBy: req.user?.id || MASTER_ADMIN,
OR, using nullish coalescing operator:
 `req.user.is ?? MASTER_ADMIN`
 If the left hand side was falsy value the right hand side will be selected.
 What are falsy values? see [this](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) and for more fun [check that](https://www.freecodecamp.org/news/falsy-values-in-javascript/)

2022-08-15 08:47 UTC, Jood80 commented on src/controllers/users/addUser.ts
> +      createdBy: req.user?.id || MASTER_ADMIN,
What's the point of the `?` with `||` here anyway?

2022-08-15 08:47 UTC, Jood80 commented on src/controllers/users/editProfile.ts
> +    userUpdatedFields.updatedBy = req.user?.id;
Add a fallback id in case this dude was undefined

2022-08-15 08:50 UTC, Jood80 commented
You have forgotten conflicts waiting to be solved to :)

2022-08-15 09:51 UTC, Ibrahim-Jarada approved these changes

2022-08-15 10:57 UTC, zaher-aa approved these changes

2022-08-16 06:04 UTC, Jood80 commented on src/services/user/userStatus.ts
> +<<<<<<< HEAD
same here

2022-08-16 06:04 UTC, Jood80 commented on src/helpers/validation/index.ts
> +>>>>>>> 255f3e04629fbbbbf0e8f54d6f1fb87e6153d7c6
Are these lines okay to have?

2022-08-16 06:10 UTC, Jood80 approved these changes

2022-08-16 07:13 UTC, merged