36/fix leftovers problem
NextUp-comedy/api-nc pull request #41
Opened 2022-09-01 06:29 UTC by RandSohail

### To be fixed:
- [x] #37
- [x] unify the sent message to the user when signup to be `user does not exist` instead of exposing his/her current status `PENDING | REJECT | APPROVED` in `registrationChecks`
- [x] handle reason of rejection coming from the front to `api/v1/user/reject/:id`
- [x] handle waiting list pagination
- [x] validate the email to follow a regex & handle the validation error to be sent to the front through a msg.
- [x] change the sent message when the user enter their already approved email to be something else than that `CHECK EMAIL` to distinguish it from other messages.
- [ ] handle this error occurred Google login/signup process
    <img src="https://user-images.githubusercontent.com/56412800/185908990-0dc093b1-c8fe-4bb3-aab2-adffaf3dd17f.png" width=700 hieght=200 />
- [x] create a controller for changing passwords.

2022-09-08 10:15 UTC, Ibrahim-Jarada requested changes
Good Job in general!

2022-09-08 10:40 UTC, Ibrahim-Jarada requested changes
Security Problem

2022-09-08 10:40 UTC, Ibrahim-Jarada commented on src/middleware/checkUserRole.ts
> +    req.app.set('user', userData);
!Important, This is a global setting as we use a lot of async functions users requests may affect others ones and that will lead to unexpected behavior (high severity vulnerability)

2022-09-08 10:44 UTC, zaher-aa requested changes

2022-09-11 08:09 UTC, Ibrahim-Jarada approved these changes

2022-09-11 08:16 UTC, zaher-aa approved these changes

2022-09-11 08:19 UTC, zaher-aa commented
**DO NOT** merge this pull-request until refactoring the front end side, so the endpoints we use in the front end match the ones we have in our API

2022-09-11 10:44 UTC, Jood80 approved these changes
such a great job you've done here, Rand!! 🔥 
please give the comments I left to you a look

2022-09-11 10:44 UTC, Jood80 commented on src/helpers/errorMessages.ts
> +export const NOT_EXIST_ERROR = new CustomError(
Nice move!!
Optionally, as you're already calling them as `errroMesseges.NOT_EXIST_ERROR` I would suggest to remove the `_ERROR` word

2022-09-11 10:44 UTC, Jood80 commented on src/helpers/validation/createUserSchema.ts
> -  roleId: Joi.number().required(),
I would suggest to add an extra layer of validation here, say:
```
Joi.number().valid(1, 2, 3).isRequired()
```
for instance

2022-09-11 10:44 UTC, Jood80 commented on src/helpers/validationRules.ts
> +// export const uri = Joi.string().uri().required();
what's the purpose of these commented lines?

2022-09-11 10:44 UTC, Jood80 commented on src/middleware/checkUserRole.ts
>    _res: Response,
you're naming them one of them `request` and the other one `_res`, make up your mind 👓

2022-09-11 10:44 UTC, Jood80 commented on src/middleware/checkUserRole.ts
>      const userPayload = await verifyToken(accessToken);
```suggestion
    const { id } = await verifyToken(accessToken);
```

2022-09-11 10:44 UTC, Jood80 commented on src/routes/contents/index.ts
> +router.get('/un-match-contents', validator.query(getPaginatedDataSchema), getUnMatchContent);
Preferably: `/unmatched-content`

2022-09-11 10:44 UTC, Jood80 commented on src/services/contents/getUnMatchContents.ts
> +export default getUnmatchedContent;
change it's file name too, to `getUnmatchedContent` instead of `getUnMatchContents`

2022-09-11 10:45 UTC, Jood80 commented
And please solve the conflicts too

2022-09-12 10:04 UTC, merged