update match content
NextUp-comedy/api-nc pull request #51
Opened 2022-09-03 10:29 UTC by Ibrahim-Jarada

Relates #48

2022-09-03 13:27 UTC, Jood80 requested changes

2022-09-03 13:27 UTC, Jood80 commented on src/controllers/users/matchUserContent.ts
> +    };
When do you start thinking that this object shouldn't be here?
despite the fact that you should only include your pure logic in your controller -without any service explicitly implemented "just to be called"-.  any objects that has to be processed before being used in the code, either to convert its type or to make any sort of modification over it should be moved onto `dto` object.
your controller should be as clean as possible, so others can quickly grasping what's the logic behind it

2022-09-03 13:27 UTC, Jood80 commented on src/controllers/users/matchUserContent.ts
> +    if (body.recoveredCosts > (body.filmingCosts + body.advance + body.feePaid)) throw new CustomError("Recovered costs can't be greater than costs", 400);
```suggestion
const remainingCost = body.filmingCosts + body.advance + body.feePaid
    if (body.recoveredCosts > remainingCost ) throw new CustomError("Recovered costs can't be greater than costs", 400);
```
if those accumalted values aren't `remaingCost` and instead are `accumulatedCost` or `totalCost` then pick whatever you see is more accurate and rename it

2022-09-06 06:32 UTC, Jood80 approved these changes
Nicely done Ibrahim! 
it's impressive to see you carefully covering these cases!
I would suggest to add some sort of comments in your `matchUserContent` service tho, it will make it more comprehensible.

2022-09-06 06:32 UTC, Jood80 commented on src/services/user/matchUserContent.ts
> +  console.log('settings was updated');
`logger.success` maybe?

2022-09-06 06:32 UTC, Jood80 commented on src/services/user/matchUserContent.ts
> +    if (!report) throw Error();
that `Error()` has to be updated with what we're using as a `CustomError` for now

2022-09-06 06:32 UTC, Jood80 commented on src/services/user/matchUserContent.ts
>  type IMatchUserContent = (_: {
please update this as @Mohammed-Hamada suggested in [his issue](https://github.com/NextUp-comedy/api-nc/issues/44)

2022-09-06 07:24 UTC, zaher-aa approved these changes

2022-09-06 07:43 UTC, RandSohail approved these changes

2022-09-06 09:18 UTC, AymanSami98 approved these changes

2022-09-06 09:18 UTC, merged