general edit, link front with the back
NextUp-comedy/api-nc pull request #6
Opened 2022-07-06 20:51 UTC by RandSohail

2022-07-07 12:48 UTC, Jood80 commented on src/controllers/auth/resetPassword.ts
> +    res.json({ message: 'User already verified' });
Typically, your endpoint `CLIENT_BASE_URL` or whatever you wanna call it -which is in this case=`http://localhost:3000`-; should be recalled from your `.env` file for many reasons, one of them is for a faster maintainability, so that whenever you gonna change your production link, you'll do it once at one place.

2022-07-07 12:48 UTC, Jood80 commented on src/middleware/isAuth.ts
> +import { verifyToken } from '../utilities/jwt';
A nice thing to be considered when your imported paths start getting redundant as in line 3 & 4, is to use predefined absolute paths (path mapping) in you `tsconfig.json` file. such as:
```
"compilerOptions": {
     "paths": {
          "@utilities/*": ["utilities/*"],    
    },
  ```
  [check this is out](https://stackoverflow.com/a/43330003/15107393)

2022-07-10 09:43 UTC, Jood80 commented on src/middleware/isAuth.ts
> +import { verifyToken } from '../utilities/jwt';
Oh! `paths` is already included in your `tsconfig.json`! However, when I tried using it in `login.ts`, I got this: 
<img src="https://user-images.githubusercontent.com/56412800/178138152-ca6c8b6c-2c4f-4dbe-b103-a880739ae55b.png" height=80 width=500 />
So here is few modifications that would resolve this problem for you:
-   Update your `tsconfig.json`:
     ```json
      "baseUrl": "./server/src",  // instead of "." 
      "paths": {
          "@database/*":["database/*"],  // not ["src/database/*]
          "@utilities/*": ["utilities/*"], 
          "@utilities": ["utilities/index"],  // if you want to import from your index.ts directly.
           ...
      ``` 
 - If the error hasn't gone by now, and you're a Vscode user; hit:  `Ctrl +Shift + p` > `Eslint: Restart Eslint Server`.

-  Finally, you need to know that if you'd run your `test` script it will fail finding the paths, so an update in your `jest.config` would be also required: 
    ```js
    moduleDirectories: ['node_modules', 'server/src'],
    moduleNameMapper: {
        "@database/(.*)": "database/$1"
         ....
      }
      ```
  This should make it work -at least it did on me- and by that your module imports might look more readable now.
  _**HOWEVERR**_
  I just ran into this **cool answer** >> [please give it a look](https://stackoverflow.com/a/70368654/15107393 ).
 and it might be a good idea to forget all what I've just mentioned earlier :)

2022-07-13 05:51 UTC, zaher-aa commented on src/middleware/isAuth.ts
> +import { verifyToken } from '../utilities/jwt';
Wow!!
Thanks Nujoud for this amazing review!

2022-07-13 06:50 UTC, Jood80 commented on src/middleware/isAuth.ts
> +import { verifyToken } from '../utilities/jwt';
Not really 😁 
absolute paths doesn't seem to be a good practice after all -as in the last shared link above-
So we may stick with the relative paths for now regardless seeing it as an ugly creature.

2022-07-17 11:01 UTC, Jood80 commented on src/database/models/Users.ts
> +  isRejected?: boolean;
what's the difference between `isApproved` vs `isRejected` ?

2022-07-17 11:49 UTC, RandSohail commented on src/database/models/Users.ts
> +  isRejected?: boolean;
isApproved when the system admin approves the user account
isRejected  when the system admin rejects the user account
disable when the system admin disables the user account => will be added
isVerified when the user verifies his account => will be added

2022-07-17 12:16 UTC, Jood80 commented on src/database/models/Users.ts
> +  isRejected?: boolean;
Having a `status` field such that:
`status:  verified | pending | canceled | rejected` might be more comprehensible. 
we have four fields relatable in their functionality in here.

2022-07-18 18:06 UTC, AymanSami98 approved these changes

2022-07-19 19:32 UTC, NoureldeanSaed requested changes
> **NOTICE**: Changes requested to this branch should not be ignored, but the branch must not block anything else and should be merged with development even if some changes were put up for later

**General notes**
Use typescript
DRY code

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/controllers/auth/forgetPassword.ts
> +    if (!user) return res.json({ message: 'User does not exist.' });
- Always put all of your messages/strings in a separate file, separating your messages will allow you easy swapping to a different language, and will make your messages more consistent.

- Always send error codes with errors, especially errors, you send 201 and 302, but not 403? 

- Opinion: Friendly messages are not the specialty of backend, backend should return error codes and status codes, frontend as the interface has the responsibility to show these error codes in readable format.

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/controllers/auth/forgetPassword.ts
> +      roleId: roleId || 0,
Are you using typescript? Not seeing a single type, what are the possible variations of roleId? What is this `0`? Why is none of this typed? 

Goes for the rest of the files.

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/controllers/auth/login.ts
> +    console.log(roleId);
Remove logs.

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/controllers/users/approveUser.ts
> +    const user = await Users.findOne({ where: { id: userId, isVerified: true } });
You have repetitive code, fetching the user, then checking if the user exists, then if they're approved, then if they're rejected, etc.

Create custom helpers that help you do a bunch of these actions at once, and reuse that, instead of copying code.

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/controllers/users/approveUser.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
No one ever wants to see this, remove all `any` definitions in your project instead of muzzling eslint.

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/controllers/users/getApprovedUsers.ts
> +    // if (req.admin) {
Remove commented code.

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/database/models/Users.ts
> +      // allowNull: false,
Remove commented code.

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/middleware/isAuth.ts
> +  } catch (err: any) {
I don't even know why would you specify `any` to the error type. What did that contribute? What information is given by saying that the error can be literally anything ever?

2022-07-19 19:32 UTC, NoureldeanSaed commented on src/routes/index.ts
>  router.use('/auth', authRouter);
Separating routers is very good practice :clap: .

2022-07-24 11:18 UTC, Jood80 approved these changes

2022-07-24 11:56 UTC, AymanSami98 approved these changes

2022-07-24 12:06 UTC, Ibrahim-Jarada approved these changes

2022-07-24 12:13 UTC, zaher-aa approved these changes

2022-07-24 12:13 UTC, zaher-aa commented on package.json
>      "start": "NODE_ENV=production node ./server/dist/bin/index.js",
```sh
"start": "NODE_ENV=production node ./dist/bin/index.js",
```

2022-07-24 12:15 UTC, merged