7 update email service
NextUp-comedy/api-nc pull request #7
Opened 2022-07-22 16:41 UTC by Jood80

## In This PR:

- [x] switch from [nodemailer](https://nodemailer.com/about/) to [sendgird](https://sendgrid.com/) service.
- [x] update email templates.

* **effected endpoints**:
    1.  `POST`: `api/v1/auth/signup/` - as User
    2. `POST`: `api/v1/auth/login/` - both User & Admin 
    3. `GET`: `api/v1/user/notApprovedUsers/` - as Admin
    4. `POST`: `api/v1/user/approveUser/:userId` - as Admin
    5. `POST`: `api/v1/user/rejectUser/:userId` - as Admin
    6. `POST`: `api/v1/auth/forgetPassword` - as User
    7. `POST`:`api/v1/auth/resetPassword` - as a User. 
---
### Pricing:
- with our free plan now, we can send up to 100 emails/day.
- exceeding that free amount, to send between [1000 - 50,000] email/month, will cost us/them ~$19.95/monthly.
for more [see pricing section](https://sendgrid.com/pricing/).
-----
### Email Templates:
- [x] the user should be expecting 4 different email types from us:
  - Verification email
  - Approval Email
  - Rejection Email
  - Reset password email
<div align="center">
<img src ="https://user-images.githubusercontent.com/56412800/180400838-7f051fc2-0195-4013-af97-2192e36c6fb6.png" height =230 width=150 />
<img src ="https://user-images.githubusercontent.com/56412800/180402584-0fc75d49-81f4-45ba-8b18-4747fe77cc07.png" height =230 width=150 />
<img src ="https://user-images.githubusercontent.com/56412800/180403075-2ea20423-cc51-4999-9d3a-c58620daf6f9.png" height =230 width=150 />
<img src ="https://user-images.githubusercontent.com/56412800/180403835-47ff2222-8e44-47ae-92d9-a7bbba60a6e6.png" height =230 width=150 />
</div>

----
## Testing
#### Env Config
1. setup your backend environment.
   -  <details>
      <summary>create `.env.development` with these variables.</summary>
      
      ```
        PORT=5000
        DATABASE_URL = postgres://<USERNAME>:<PASSWORD>@localhost:5432/nextup_comedy_dev
        TEST_DB_URL = postgres://<USERNAME>:<PASSWORD>@localhost:5432/nextup_comedy_test
        JWT_SECRET=<IT_IS_CALLED_SECRET_FOR_A_REASON>
        NODEMAILER_APP_MAIL = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        NODEMAILER_MAIL_PASSWORD = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        CLIENT_BASE_URL = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        SERVER_BASE_URL = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        
        SENDGRID_ADMIN_EMAIL = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        SENDGRID_API_KEY = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        SENDGRID_VERIFICATION_TEMPLATE_ID = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        SENDGRID_RESET_PASSWORD_TEMPLATE_ID = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        SENDGRID_APPROVAL_TEMPLATE_ID = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        SENDGRID_REJECTION_TEMPLATE_ID = <IT_IS_CALLED_SECRET_FOR_A_REASON>
        NEXTUP_COMEDY_SUPPORT_EMAIL = <IT_IS_CALLED_SECRET_FOR_A_REASON>
      ```
      </details>
  - `$ npm run build:db` >`$ npm run insert:db`
  - `$ npm install `:
     -  `$ npm run dev`
     - OR : create `.env` > `$ npm run build` > `$ npm run start`
 2. For a better dev experience, run your front repo too:
    - clone `https://github.com/NextUp-comedy/front-nc`
    - setup your `.env` file with:
      - <details>
         <summary>front env vars</summary>
       
         ```
            REACT_APP_CLIENT_ID = <XXXXXXXXXXX>
            REACT_APP_CLIENT_SECRET=XXXXXXXXXXXXXXXX
            SKIP_PREFLIGHT_CHECK=XXXX
         ```
        </details
    - `$ npm install` > `$ npm start`
----
#### Test this PR:
 1. Go to `api/v1/auth/signup/`:
      - Request "create user DTO"
       ```ts
       {
        "username": "your new name",
        "email": "valid_email@gmail.com",
        "password": "not_less_than_6_char"
       }
    ```
    - expected Response:
    ```ts
      {  "message": ""Check your email"   } // check your Email. " Spam / Primary / Promotions/ Updates / wait for half a min max if it wasn't there yet & make sure you've written your email correctly. 
     ```
2. See how the whole journey goes in this video 👇🏽 : 
   https://www.loom.com/share/bd8fbc4387b84a398cbf42d447d1b581

2022-07-24 13:28 UTC, AymanSami98 approved these changes

2022-07-26 19:41 UTC, Jood80 commented
An undesired behaviors have occurred here after the last merge.
Will need to tweak them then ask for your review again.

2022-07-27 09:03 UTC, zaher-aa requested changes

2022-07-27 09:03 UTC, zaher-aa commented on src/controllers/users/approveUser.ts
> +  const redirectURL = `${config.server.clientURL}/`;
The `/` after the clientURL is for what?
```suggestion
  const redirectURL = `${config.server.clientURL}`;
```

2022-07-27 09:03 UTC, zaher-aa commented on .eslintrc.json
> +
Why did you add these rules?

2022-07-27 09:18 UTC, Jood80 commented on src/config/email.ts
> +}).unknown().required();
YUP, was just about to fix those in the next push 👍🏽

2022-07-27 09:22 UTC, Jood80 commented on src/config/email.ts
> +  };
Absolutely right in case those are variables, but they ain't.

2022-07-27 14:54 UTC, Jood80 commented on .eslintrc.json
> +
I'm keeping the `no-shadow` part only for now, as I ran into this problem in `src/interfaces/email.ts` file
![image](https://user-images.githubusercontent.com/56412800/181278155-4becf3c4-914a-41b1-8e1c-aa02195d1ac4.png)

The cute thing that I AM NOT declaring it somewhere else, which was confusing somehow.

2022-07-27 16:47 UTC, RandSohail approved these changes

2022-07-28 08:10 UTC, zaher-aa approved these changes

2022-07-28 08:10 UTC, merged

2022-07-28 08:10 UTC, zaher-aa commented
👍