Payouts
NextUp-comedy/api-nc pull request #84
Opened 2022-10-02 08:47 UTC by Ibrahim-Jarada

Relates #63

2022-10-02 20:38 UTC, RandSohail requested changes

2022-10-02 20:38 UTC, RandSohail commented on src/controllers/users/getUserPayouts.ts
> +  const { user } = dto.generalDTO.userDTO(request);
The same thing create new DTO and make whatever you want there, DON'T USE TOW

2022-10-02 20:38 UTC, RandSohail commented on src/controllers/users/askPayoutRequest.ts
> +export default async (request: Request, response: Response, next: NextFunction)
The request type you use in [this](https://github.com/NextUp-comedy/api-nc/blob/abf24f9870a2ef7b5b4a60e8495e78e6a937e320/src/helpers/dto/users.ts#L31) is an `IUserRequest`, I believe you should use  the same type in the controller

2022-10-02 20:38 UTC, RandSohail commented on src/controllers/users/askPayoutRequest.ts
> +    if (+amount <= 0) throw errorMessages.NO_BALANCE;
Why is the amount in the [DTO ](https://github.com/NextUp-comedy/api-nc/blob/abf24f9870a2ef7b5b4a60e8495e78e6a937e320/src/helpers/dto/users.ts#L33) is a string then when using it you transfer it as a number?
why not transfer it as a number in the DTO?

2022-10-03 09:39 UTC, AymanSami98 approved these changes

2022-10-03 14:21 UTC, zaher-aa approved these changes
الله أكبر عليك, ايه الحلاوة دي!

2022-10-03 14:33 UTC, merged